# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/16_spark.ipynb (unless otherwise specified).

__all__ = ['create_spark_session']

# Cell
import pyspark
from pyspark.sql import SparkSession

def create_spark_session(settings: dict):
    """
    Boots up a SparkSession object manager to handle parallelized operations
    """
    session = SparkSession.builder
    if not settings.get('spark'):
        return SparkSession.builder.getOrCreate()
    for parameter, value in settings['spark'].items():
        session = session.config(parameter, value)
    return session.getOrCreate()